//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveKart.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public long LoginID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int RoleType { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<short> IsLocked { get; set; }
        public int InvalidAttempts { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
